# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Article.create(title: "", description: "", author: "", date: "", readtime: "", image_url: "", content: "")
Article.destroy_all

Article.create(title: "How and where to start as a front-end web developer", description: "No one is exaggerating when they say now is the best time to start learning web development. This isn't one of those fad careers. The field is projected to grow 10% for the next decade. But there's a catch to it. You have to be able to learn the skills and it's not always as straightforward as it seems. There's a lot of stuff to sift through so here's a quick way to get through it.", author: "Milecia McG", date: "14 Jan 2018", readtime: "3 min read", image_url: "blog1.jpg", content: "Commit to learning the technical stuff
Once you make the decision to become a front-end developer then you need to be 100% in. It's no harder than learning anything else once you start putting the work in. You just need to be determined to keep going until you get it all figured out.
It's ok if you have to slow down or take a break as long as you know without a doubt that you will come back to it and speed up. Changing your mindset to have the confidence to learn how to program sounds corny, but it's even more important than the technical skills themselves.
The reason you need this mindset is because you never stop learning as a developer. There's always new versions of packages to deal with, updates to programming languages and standards, and new ways for your code to break. There will be times where you hit an issue that will push you to your technical limits and that commitment makes the difference between you pushing through and you falling out.
Go through some free material
You can find so much free stuff on front-end web development that it would be a shame if you started anywhere else. Go through some of those free tutorials and videos! That’s how you'll figure out if this is really for you. Start writing some sample code and read as much as you can about HTML, CSS, and JavaScript.
After you've gone through a few different tutorials and guides, try building a project from scratch. It doesn't matter if you think it's good or not, start writing code. If you like this, good! Keep going! If you don't, it's cool. You didn't spend any money and you did learn something that most people won't even attempt.
Decide if you need more help.
When you've been through more tutorials than you can remember it gets to the point where you feel lost. You're not quite sure what to do next and sometimes it's hard to get a foothold on the next step. That's when you have to start making some important decisions that will shape who you become as a developer.
You can stay on the self-taught path and muddle through some documentation and a lot of Stack Overflow. Or you can pay for someone to show you exactly what you should be doing and how to do it. There are coding boot camps, online classes, and some college courses on front-end web development.
Keep in mind that you will always be self-taught to some extent. Even when you get a job you'll be digging through documentation and Stack Overflow. The purpose of the paid services is to get you up to junior dev status faster than you could do on your own. So keep this in mind as you take those first steps into front-end development. You aren't the only one with questions.
These are a few of the things that you can do to get started as a front-end web developer. The most important thing is still getting your mind wrapped around the fact that you are going to be a web developer. The rest is considerably easier when you aren't fighting the urge to do something else.")

Article.create(title: "The significance of SEO Website Design", description: "‘Beauty lies in the eye of the beholder' is the truly relevant phrase that goes with your website design. The design of any site is determined by the visitors and not the website owners. There are numerous features that you need to consider when creating a website to increase the number of users in your site. Not just the appearance, you must also ensure that your website is user-friendly.", author: "Lakshmi Priyanka", date: "27 Jan 2019", readtime: "4 min read", image_url: "blog2.jpg", content: "If your website is not designed appropriately, it is likely to perform poorly and have high bounce rates, fewer pages per visit and low conversion rates. When forming a website, you must assure that not only your website can attract potential customers but also making the customers stay for a considerable period. By reading this article, you will be able to explore the practical principles of web design. It will guide you to create an aesthetically appealing, engaging and easy to use a website for your company.
Basic principles of a successful website
Firstly, you need to determine the purpose of your website. Most business owners create their websites to connect to the world and develop a center of attention for new users in the online marketplace. Successful custom ecommerce web design services always facilitates the users and offer them all the necessary pieces of information that they will need to understand the motive of your company. Make sure that every page of your website display a clear purpose and be able to meet the expectations of the visitors in the best way possible. If you are searching for customers who want to transact with your company, then the above-stated principles are mandatory. You need to help them attain a comfortable experience when dealing with you.
In today's hectic schedule, people are impatient and do not have time to wait for long to get the information they want. Thus, your site must be able to communicate with the users clearly in minimum time. You must provide information that is easy to read and understand. Including topics and subtitles is an efficient method to display any content in your web pages. Try to add bullet points instead of lengthy descriptions. Avoid providing unnecessary substance that irrelevant for your company.
Utilize colors to make your site look pleasing
Designing your website redesign in a better way with the latest layouts and technology is an excellent way to enhance customer experience. Adding colors, designs, and textures that meet the taste and concept of your company can offer a visual treat to the customers. Using complementary colors for the background and writing texts will make the content appear more transparent. Vibrant colors are brilliant for connecting with the users and try to use them carefully for a call to actions or buttons in the material. Do not fear white spaces on your website. Areas give your website a modern and organized look. Too much of texts and images all over the page can make it look dull and uncluttered.
Include images to grab attention
Consider inserting some suitable images on your content that can enhance brand visibility of your company. With the apt pictures, you can connect with the target audience and create awareness among them about your company. In case you do not know what to post, purchase some stock photos to improve the appearance of your website. You can also use graphics, animation, and videos to your website which can turn out to be more useful to grab users' attention than the best-written texts.
Need for a better website designing
In today's global marketplace, having a website is not enough. Your site should be mobile-friendly and be able to adopt any device or screen size. People using smartphones are increasing day-by-day. According to surveys, the majority of the population prefer mobile phones to surf the internet and purchase products online. Ensure that your website is optimized for mobiles to help it load in all kinds of devices, irrespective of the screen sizes.
People often tend to boycott websites that take a lot of time for loading. You must continue to test your website at regular intervals to help it work smoothly. The images and videos that you include in your content should be optimized or compressed in a JavaScript or CSS file which improves the speed of the loading time.
You cannot achieve success through your website by just excelling in certain aspects. You need to have a website designed with better functionality that complements the content of your web pages. It should be able to communicate with the users in an efficient manner, assuring that you are not driving away any user. To ensure that your site can meet the requirements of your users, mapping out your customer's journey is essential.
Digital SEO is a best web design in chennai, which is well-established firm that employs professional designers with six years of experience. Opting for Digital SEO for crafting a compelling and engaging website can be an ideal deal. The expert designers will ensure that your website is optimized for all kind of devices. The various tactics and strategies of the firm can enhance your brand’s visibility in the online market.")

Article.create(title: "404 Page Not Found — Something needs your attention", description: "That beautiful website you worked so hard on and checked 12 times for glitches before launching harbors a sleeping saboteur. For reasons unknown and mysterious, what once worked will break. And you don’t even have to be in the room.", author: "Gregory Anne Cox", date: "18 July 2018", readtime: "3 min read", image_url: "blog3.jpg", content: "That perfect image you finally found for your best blog post this month will, instead of the sun glinting on the sea, appear with a blank rectangle framing a question mark.
No sun. No sea. Fail.
Broken links, missing images, videos that won’t play and products you no longer offer but live on your site all have one thing in common: they drive people away from you, but first they annoy them.
One way to sooth the sting of those frustrations is to get creative with your 404 or “error, page not found” page.
Do you know what yours looks like right now? If you do, is it branded?
If yes, you get an A for effort — and there is more to do.
The goal of the page is to assuage and apologize — sort of — for something that could be your fault. They also could have typed the URL in wrong, but let’s discard our need to be right just this once. The seeker has reached an impasse and you have the chance to show them an alternative route to enlightenment. You’ll be the hero of the moment!
Here are 5 things your 404 page can do — the first two are musts.
*Brand the page. Write the message in the voice you use in all of your communication.
*Include a link to your home page or include your site’s navigation at the top
*Use humor because this is a situation that calls for levity people
*List a couple of reasons they might have landed there: A link broke, we removed the thing you were looking for, the dog ate it.
*Suggest they read one of your best blog posts — with image — then link to it
Here are 4 of my favorites from around the web, so you’ll get an idea of the different ways this important and often-neglected page can make a difference for your business:
Hubspot It’s branded, they have their nav bar at the top, and they own that something went wrong on their end and ask for your patience while they “put things back together.” Then they direct people to their blog, product page, and offer a link to a free demo.
The Onion If you don’t know the onion but you love satire and need a good laugh about the current state of world affairs, subscribe to their newsletter. You’ll get a sense of their sarcastic wit from their error page. So well done. And they offer a phone number for customer service on top of linking to their homepage.
Dave Barton Is a blogger and writes his like a dating ad. Sometimes just getting the message that you’ve gone somewhere in error works.
Amazon Who doesn’t like a cute dog? Sure to soothe savage searchers. What else they do well is the navigation at the top, a link to the home page, and a link to meet “the dogs of Amazon.” Who knew they had dogs but it’s a great engagement tool.
Speaking of broken links, here are two services that will detect broken links and other potential problems: Link Patrol, which is priced as a one-time fee, and Screaming Frog SEO Spider, which has a free and paid version. Those are not affiliate links and I have not used either, but I am going to go with Link Patrol because for $50 to crawl my site and update-check it every time I add something for one year, it’s a bargain.
Let’s wow and love on those who seek to learn more about us and our services, not drive them mad. Things will break and servers will go down. By taking the time to be a wee bit entertaining, we are making the broken world a better place.")

Article.create(title: "6 Attributes That Show You Are A Good Developer", description: "There are some things that show you really know what you're doing and of course those are the things you want to work one. As a web developer, you need more than just technical skills. You need to be able to communicate with bosses, clients, co-workers, and other people. It sounds a little odd, but in time you'll need to be able to communicate with yourself because it's easy to forget what your code does after three years.", author: "Milecia McG", date: "26 Dec 2018", readtime: "4 min read", image_url: "blog4.jpg", content: "Here are six key attributes that every web developer or programmer in general should have:
Know how to wade through folders of legacy code.
Most likely when you get your first web dev job you won’t be starting with a fresh, new code base. You’ll sometimes get a code base that is the equivalent of a leaky pipe being held together with duct tape, glue, and whatever else they could find.
And they’ll expect you to be able to go through the code and find the bugs and maybe even do a little refactoring.
Be able to talk to people.
There is not a project you will work on that doesn’t include at least one other person. You might be working with Tiffany from HR to get the right names on the company page. You could end up with Winston, the longstanding coding expert in the company. There will be people from all backgrounds working with you.
You can’t hide behind the “awkward developer” stereotype anymore because someone who has the same skill set as you will be able to talk their way into the position you wanted. Nobody’s going to bite you when you talk and if they do, bite back.
Know how to read through documentation.
Every place will use the same languages and frameworks slightly differently. You need to know how to skim through pages of documentation and Stack Overflow answers efficiently. That way you can find what you need to make your code work the way they want it to.
Plus, the languages and frameworks are always changing. There are always new ones being introduced too. You might be in the middle of an Angular 5 project and then Angular 6 comes out (not that I’m upset or anything) and you have to start looking through documentation.
Write good documentation for your code.
This is so overlooked that it hurts sometimes. Good documentation can help you explain what you’re doing and why you're doing it and it can help other developers on the team get up to speed faster.
Just make sure you keep your documentation relevant to what people need. If there are any steps you took to get the environment setup, any software you needed to download, or any particular hierarchy of the folders, that’s what would make some good documentation.
Use best practices when writing your code.
This probably sounds obvious, but you’d be surprised how many people don’t do this. Take the time to write your code correctly the first time. That’ll save you the headache(s) of fixing it later and the other people you work with won’t hate you for writing bad code.
But seriously, using best practices will save you a lot of time and help you get your work done faster.
Test your code.
Another one that probably sounds obvious. Front-end developers are responsible for what users see on a site so you need to make sure they see the right stuff in the right way. If you know that your CSS breaks on certain elements when they are clicked, fix them!
If you know that your JavaScript doesn’t work right with certain inputs, find out why and fix it. It doesn’t hurt to do a little debugging if you have the time. It’ll help you write cleaner code and keep you from working on the same bugs for eternity.
It's the little things that matter the most. When you master these six skills, you'll still be surprised that not everyone is doing it.")

Article.create(title: "Role of Cloud in Successful App Development", description: "Over time, cloud computing technology has revolutionized the way entrepreneurs, and developers view successful app development. The emerging mobile computing and data analytics trends are set to create apps that will give a high return on user’s efforts and investment.", author: "Amit Tiwari", date: "24 Dec 2018", readtime: "3 min read", image_url: "blog5.jpg", content: "Enterprises around the world need more accessible, more efficient, and faster ways of developing apps that are suitable for enterprise requirements and customer choices, and that’s where cloud app development technology comes in. While today’s enterprises embark on using services on the fly, a handful of them use multi-cloud strategies that deploy cloud computing services through software such as IaaS environments, PaaS, and SaaS. For example, with cloud computing technology, an enterprise can use software such as Azure for their online apps and at the same time, deploy their CRM app to services such as Salesforce. That’s how enterprises around the world are using cloud technology to generate high-value propositions in the world of cloud app development.
Fully Integrated Solutions
When an enterprise is creating an app using a web-based platform, the cloud let them integrate it fully. That makes it easier to create an app that has similar features as those in the cloud platform. Consequently, an integrated app is not only created but also entirely secured as well. The fact that an enterprise uses a single platform to create an app makes web-based apps perform much higher than traditional ones.
Easy Functioning
Any enterprise or developer that uses web-based apps don’t worry about the cloud infrastructure. Instead, it is the cloud provider that doe the maintenance, which makes the cloud technology much easier to use than conventional platforms. The opportunities that the cloud technology offers to business and app developers are exclusive to them, and this has enabled developers to use various cloud platforms to build their applications.
Advanced Features
The cloud technology comes with a plethora of features which often lack in traditional app development technology. Some of these features have been instrumental in the massive transformation of the mobile app development world. New age features such as geo-location and social media networking platforms increased the efficiency of app developers and made their work pretty easier than ever. That’s the reason app developers can integrate various tasks and functionalities into their mobile apps and create as many apps as they can seamlessly.
Scalability
The cloud computing technology comes with an option for app developers to scale up their efforts allow for appropriate allocation of resources to various apps. Unlike traditional mobile app developmentplatforms, app developers don’t need to install any extra hardware. Moreover, all the cloud environment servers are available online, enabling app developers to increase the allocation of resources and the bandwidth to the app with just a single click. That ensures the app will never slow down due to insufficient funds, and such scalability is only available on the cloud app development platforms.
Cost Effectiveness
App developers outsource their servers and data centers needed to support the cloud environment from a cloud vendor. As a result, an app developer only invests in necessary resources, and the cost of the data center and the server maintenance isn’t on them, so the expense that clients incur are manageable. That has made the cost of developing mobile apps on the cloud much more affordable than ever.
Faster Speed
App developers can deploy and test an app built on the cloud technology quickly. Their accessibility is equally fast due to the cloud technology redundancy. With cloud technology, there is no delay at all, meaning that enterprises can use their apps in real time.
Over time, cloud computing technology has revolutionized the way people build their apps. It’s now quick and easier for businesses and mobile app developers to develop their enterprise-grade apps using cloud technology. Accessibility to cloud-based apps has also increased through infrastructure, platform, and software as a service. More and more app developers are integrating cloud infrastructure into their strategy to meet the needs of their clients and enhance the mobile ecosystem for apps. As a result, many app developers have now shifted to the cloud infrastructure to make it easier to create their apps.")

Article.create(title: "Top 5 Features of an Interactive Website", description: "A website is the first impression to create an interaction with your audience. A website for any type of business must detail out important aspects that you would want to expose your offerings. The website’s Design and development tasks are the two critical factors while building up a website.", author: "Suman Dhankhar", date: "28 Sep 2018", readtime: "4 min read", image_url: "blog6.jpg", content: "Successful businesses always thrive to publish their business website in the most attractive and elegant image thus giving out all the necessary information that the audience seeks to know. In today’s highly competitive technological industry, you may struggle to find the most promising Web Development Company in India as only few of them deliver the most intelligent and interactive websites. All-in-all, Creaa Designs delivers unique outputs of designs and development projects.
Now the question arises - What makes a website interactive so that the audience gets hitched? You may have found the finest of designers and developers who you believe are creative to face the challenges of today’ IT ever-trending revolution. That’s great however, what about adding the touch of “interaction”? In this section, we are going to discuss interesting facts of some key features of an Interactive Website which you should keep in mind before starting to get your website designed;
Plan and Strategy: Prepare a detailed plan and robust strategy to be followed in order to designing a website. The website can only interact with the audience if it has an interface that’s gorgeously attractive and gives a smooth browsing experience. Next, decide what elements you need to display on the website and at which position, so that it meets the criteria of audience’s easy visibility. Imagine it from the perspective of different prospective audience who will be visiting your website through Google. Therefore, getting started with the right plan and the right strategy will show a clear roadmap to succeed in designing the most fascinating website.
Technology and Cost: Deciding on the technology is critically important and its cost will totally depend upon the web technology used in order to develop a website. WordPress, Shopify, HTML, etc. are some of the many technological platforms largely used and the CMS (Content Management System) is the most common back-end panel equipped to develop the website. Determining the scope and budget is key. The two aspects; technology and cost are found pretty hard to balance off. It all depends on your business’ priority, whether you seek for the finest of technology or a cookie-cutter one where many compromises will have to be made. Make the right decision to never regret what future brings on the table.
Quality Content & Tones: Since recent years, content marketing has become the talk-of-the-town in the Digital industry. Content is King! Therefore, publishing content on the website must be interesting to read with catchy phrases, intelligent choice of words that are simple to understand and definitely must be 100% unique.
Colour tones framed on the website should give the audience a kind of an appeal to read through. The fonts should be legible, bright background to make the page attractive to glue one’s sight on. Moreover, posting captivating images relevant to the content is what captures the reader’s attention as said by many great marketers; it only takes 5-6 seconds to catch the attention of the audience.
Responsive Design: In the arena of a vast variations of display screen sizes and resolutions, it has become a great deal to by-default transform webpages viewable on every screen size i.e. Mobiles, Tablets, Laptops, Desktops, etc. If you webpage looks scrambled on certain screen sizes or resolutions, it will discourage the audience to stay any longer on the page resulting in increased bounced rates, thus losing a prospect client or customer.
Contact Information and Social Media Links: Once you have succeeded in designing and developing the most comprehensive and interactive website that has enthralled the audience to know more about you, it is obvious that they need to find you, contact you i.e. additionally explore you. You make that possible when you have clearly mentioned your business location, contact number, email address on your website. This makes it not only convenient for the audience to contact you but also give them a sense of confidence about you. Try making it more convenient by showcasing your location via google-map display staged on your website.
Apart from your contact information, you should exhibit your business presence on the many available social networking platforms like Instagram, Facebook, LinkedIn, Twitter, Google+, etc. so that it creates an additional channel for your audience to reach out to you and build a robust confidence in your offerings.
Conclusion: Websites that attract dense traffic and has high user-retention are highly interactive in its built. If you are in search of the most innovative and creative Web Design Company in Mumbai then Creaa Designs should be your best pick as their approach to keep their clients business objectives have always been their prime focus, subsequently delivering the most fascinating and interactive website that result in optimized lead generation.")
